version: '3.8'

services:
  chat_service:
    container_name: chat-service
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - '.:/app/chat_service:'
      - '/app/node_modules'
    ports:
      - 8000:8000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - main

networks:
  main: