version: '3.8'

services:
  db_oficina:
    container_name: db-oficina
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
        - .env
    networks:
      - main
    ports:
      - 5432

  py_etl:
    container_name: py-etl
    build:
      context: ./scripts
      dockerfile: Dockerfile
    
    depends_on: 
      - db_oficina

    links:
      - db_oficina

    environment:
      WAIT_HOSTS: db_oficina:5432
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 10
      WAIT_HOST_CONNECT_TIMEOUT: 45

    networks:
      - main

  chat_service:
    container_name: chat-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - '.:/app/chat_service:'
      - '/app/node_modules'
    ports:
      - 8000:8000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - main

networks:
  main: